# conda env create -f environment.yml && conda activate tjeecc
name: tjeecc
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy=2.0.2
  - scipy=1.13.1
  - pandas=2.2.2
  - pyarrow=17.0.0
  - matplotlib=3.9.2
  - tqdm=4.66.5
  - ase=3.23.0
  - pymatgen=2024.8.9
  - pip
  - pip:
      - jarvis-tools==2024.10.30
      - numpyro==0.15.3
      - arviz==0.19.0
      - SALib==1.5.1
      # Install a hardware-matched jax yourself; CPU default:
      - jax[cpu]
